services:
  postgres:
    image: postgres:16-alpine
    container_name: command-manager-db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

volumes:
  postgres_data:
